#!/usr/bin/env node
/* eslint-disable no-console -- a CLI; stdout is its interface */
/**
 * Generates avp/policy-store.json: what CDK deploys to each environment's Amazon Verified
 * Permissions store (P11.6), and what the drift check compares a deployed store with.
 *
 *   node tools/generate-avp.mjs          write the file
 *   node tools/generate-avp.mjs --check  exit 1 if the file is out of date
 *
 * The store holds only static policies from this package (ADR-005 §2); per-event permissions
 * are RolePermission rows the app passes as entity data, so the store never changes at runtime
 * and drift is "store ≠ this file" with no exclusions. The schema is Cedar's JSON form with
 * types resolved, which AVP's STRICT validation reads.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as cedar from '@cedar-policy/cedar-wasm/nodejs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'avp', 'policy-store.json');

function schemaJson() {
  const result = cedar.schemaToJsonWithResolvedTypes(
    readFileSync(join(ROOT, 'schema.cedarschema'), 'utf8'),
  );
  if (result.type !== 'success') throw new Error('schema.cedarschema does not convert');
  return result.json;
}

function policies() {
  const byId = [];
  for (const file of readdirSync(join(ROOT, 'policies'))
    .filter((f) => f.endsWith('.cedar'))
    .sort()) {
    const parts = cedar.policySetTextToParts(readFileSync(join(ROOT, 'policies', file), 'utf8'));
    if (parts.type !== 'success') throw new Error(`${file} does not parse`);
    for (const statement of parts.policies) {
      const id = /@id\("([^"]+)"\)/.exec(statement)?.[1];
      if (!id) throw new Error(`${file}: a policy has no @id`);
      byId.push({ id, statement: statement.trim() });
    }
  }
  byId.sort((a, b) => a.id.localeCompare(b.id));
  const ids = new Set(byId.map((policy) => policy.id));
  if (ids.size !== byId.length) throw new Error('duplicate policy @id');
  return byId;
}

const text = `${JSON.stringify(
  {
    $comment:
      'GENERATED by tools/generate-avp.mjs from schema.cedarschema and policies/. Do not edit.',
    schema: schemaJson(),
    policies: policies(),
  },
  null,
  2,
)}\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    // missing counts as out of date
  }
  if (current !== text) {
    console.error('avp/policy-store.json is out of date: run node tools/generate-avp.mjs');
    process.exit(1);
  }
  console.log('avp/policy-store.json is up to date');
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT}`);
}
