#!/usr/bin/env node
/** The schema owns identifiers; the separate owner decision owns fixed role floors. */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format } from 'prettier';
import { GROUPS, schemaJson } from '../lib/catalogue.mjs';
import { minimumRoles, ROLE_RANKS } from '../lib/minimumRoles.mjs';
import { actionOutputOptions, applyActionOutputs } from './actionOutput.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const options = actionOutputOptions(ROOT, process.argv.slice(2));
const compare = (left, right) => (left < right ? -1 : left > right ? 1 : 0);

function catalogue() {
  return Object.entries(schemaJson().SPOH.actions)
    .filter(([id]) => !GROUPS.includes(id))
    .sort(([left], [right]) => compare(left, right))
    .map(([id, definition]) => ({
      id,
      groups: (definition.memberOf ?? []).map((group) => group.id).sort(compare),
      principalTypes: [...definition.appliesTo.principalTypes].sort(compare),
      resourceTypes: [...definition.appliesTo.resourceTypes].sort(compare),
    }));
}

function renderArray(name, values) {
  return `export const ${name} = ${JSON.stringify(values, null, 2)} as const;\n`;
}

function render() {
  const actions = catalogue();
  const readJson = (file) => JSON.parse(readFileSync(join(ROOT, file), 'utf8'));
  const floors = minimumRoles(
    actions,
    readJson('default-grants.json'),
    readJson('minimum-roles.json'),
  );
  return [
    '// GENERATED by tools/generate-actions.mjs from schema.cedarschema and minimum-roles.json. Do not edit.',
    '// Standalone metadata: no Cedar runtime, AWS SDK or authorization decision is imported.',
    '',
    renderArray('ACTION_GROUPS', GROUPS),
    'export type ActionGroup = (typeof ACTION_GROUPS)[number];\n',
    renderArray('ROLE_IDS', Object.keys(ROLE_RANKS)),
    'export type Role = (typeof ROLE_IDS)[number];\n',
    renderArray('ROLE_RANKS', ROLE_RANKS),
    "export type MinimumRole = { readonly status: 'approved'; readonly role: Role; readonly rank: (typeof ROLE_RANKS)[Role] } | { readonly status: 'locked' } | { readonly status: 'unresolved'; readonly reason: 'owner-decision-pending' };\n",
    renderArray(
      'ACTION_IDS',
      actions.map(({ id }) => id),
    ),
    'export type Action = (typeof ACTION_IDS)[number];\n',
    renderArray(
      'EDITABLE_ACTION_IDS',
      actions.filter(({ groups }) => groups.includes('Editable')).map(({ id }) => id),
    ),
    renderArray(
      'WRITE_ACTION_IDS',
      actions.filter(({ groups }) => groups.includes('Write')).map(({ id }) => id),
    ),
    `export const ACTION_CATALOGUE = ${JSON.stringify(Object.fromEntries(actions.map(({ id, ...metadata }) => [id, { ...metadata, minimumRole: floors[id] }])), null, 2)} as const satisfies Record<Action, { readonly groups: readonly ActionGroup[]; readonly principalTypes: readonly string[]; readonly resourceTypes: readonly string[]; readonly minimumRole: MinimumRole }>;`,
    '',
  ].join('\n');
}

const generated = await format(render(), {
  parser: 'typescript',
  singleQuote: true,
  printWidth: 100,
});
applyActionOutputs(generated, options);
