-- Additive rehearsal provenance: existing rows remain live.
BEGIN;
ALTER TABLE "Registration" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "Registration_eventId_rehearsal_idx" ON "Registration"("eventId", "rehearsal");
ALTER TABLE "FootfallTick" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "FootfallTick_eventId_rehearsal_idx" ON "FootfallTick"("eventId", "rehearsal");
ALTER TABLE "CardStampEvent" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "CardStampEvent_eventId_rehearsal_idx" ON "CardStampEvent"("eventId", "rehearsal");
ALTER TABLE "GiftRedemption" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "GiftRedemption_eventId_rehearsal_idx" ON "GiftRedemption"("eventId", "rehearsal");
ALTER TABLE "Incident" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "Incident_eventId_rehearsal_idx" ON "Incident"("eventId", "rehearsal");
ALTER TABLE "LostPersonAlert" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "LostPersonAlert_eventId_rehearsal_idx" ON "LostPersonAlert"("eventId", "rehearsal");
ALTER TABLE "LostFoundItem" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "LostFoundItem_eventId_rehearsal_idx" ON "LostFoundItem"("eventId", "rehearsal");
ALTER TABLE "MissionCard" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "MissionCard_eventId_rehearsal_idx" ON "MissionCard"("eventId", "rehearsal");
ALTER TABLE "LostPersonSummary" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "LostPersonSummary_eventId_rehearsal_idx" ON "LostPersonSummary"("eventId", "rehearsal");
ALTER TABLE "Attendance" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "Attendance_eventId_rehearsal_idx" ON "Attendance"("eventId", "rehearsal");
ALTER TABLE "AttendanceChallenge" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "AttendanceChallenge_eventId_rehearsal_idx" ON "AttendanceChallenge"("eventId", "rehearsal");
ALTER TABLE "GiftStockAdjustment" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "GiftStockAdjustment_eventId_rehearsal_idx" ON "GiftStockAdjustment"("eventId", "rehearsal");
ALTER TABLE "FallbackWindow" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "FallbackWindow_eventId_rehearsal_idx" ON "FallbackWindow"("eventId", "rehearsal");
ALTER TABLE "ImportBatch" ADD COLUMN "rehearsal" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "ImportBatch_eventId_rehearsal_idx" ON "ImportBatch"("eventId", "rehearsal");
ALTER TABLE "GiftType" ADD COLUMN "rehearsalInitialStock" INTEGER NOT NULL DEFAULT 0;
DROP INDEX "Attendance_volunteerId_eventDayId_key";
CREATE UNIQUE INDEX "Attendance_volunteerId_eventDayId_rehearsal_key" ON "Attendance"("volunteerId", "eventDayId", "rehearsal");
DROP INDEX "AttendanceChallenge_issuerId_eventDayId_key";
CREATE UNIQUE INDEX "AttendanceChallenge_issuerId_eventDayId_rehearsal_key" ON "AttendanceChallenge"("issuerId", "eventDayId", "rehearsal");
COMMIT;
