#!/usr/bin/env node
/* eslint-disable no-console -- a CLI; stdout is its interface */
/**
 * Generates policies/grants.generated.cedar: one permit per Editable action, allowed when the
 * principal's per-event Role grants that action (ADR-005 §2).
 *
 *   node tools/generate-grants.mjs          write the file
 *   node tools/generate-grants.mjs --check  exit 1 if the file is out of date
 *
 * Cedar cannot compare an action with a string, so "the role grants this action" needs one
 * policy per action. The policies are static and deployed by CDK; which role holds which action
 * is entity data (Role.grants), so admins edit permissions without the app ever writing a policy.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { editableActions } from '../lib/catalogue.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'policies', 'grants.generated.cedar');

function render(actions) {
  const header = [
    '// GENERATED by tools/generate-grants.mjs from schema.cedarschema. Do not edit.',
    '//',
    '// Role policies (ADR-005 §3, layer 1): one permit per Editable action, granted when the',
    "// principal's per-event Role lists the action in `grants` (RolePermission rows).",
    '',
  ];
  const policies = actions.map((action) =>
    [
      `@id("grant.${action}")`,
      'permit (',
      '  principal is SPOH::Membership,',
      `  action == SPOH::Action::"${action}",`,
      '  resource',
      ')',
      `when { principal.role.grants.contains("${action}") };`,
      '',
    ].join('\n'),
  );
  return header.join('\n') + policies.join('\n');
}

const text = render(editableActions());
if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8');
  if (current !== text) {
    console.error('grants.generated.cedar is out of date: run node tools/generate-grants.mjs');
    process.exit(1);
  }
  console.log('grants.generated.cedar is up to date');
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT}`);
}
