import type { Action } from '../../generated/actions/index.js';

/**
 * What each Cedar action lets someone do, in plain language, as a verb phrase ("You cannot
 * …"). The permissions screen lists roles by these (P11.7); a refusal names one (P11.8).
 */
export const ACTION_LABELS = {
  'Alert.Ack': 'acknowledge a lost-person alert',
  'Announcement.Ack': 'acknowledge an announcement',
  'Announcement.SendEvent': 'send announcements to the whole event',
  'Announcement.SendStation': 'send announcements to a station',
  'Attendance.IssueCode': 'show an attendance code',
  'Attendance.MarkRoot': 'mark attendance for others',
  'Attendance.Submit': 'record your attendance',
  'Audit.Read': 'read the audit log',
  'Briefing.Complete': 'complete a briefing',
  'Card.GenerateBatch': 'print a batch of mission cards',
  'Card.Reissue': 'reissue a mission card',
  'Card.Stamp': 'stamp mission cards',
  'Card.Void': 'void a mission card',
  'Content.Edit': 'edit the event guide and map',
  'Content.Publish': 'publish the event guide and map',
  'Count.Adjust': 'adjust a count',
  'Dashboard.ReadEvent': 'see the event dashboard',
  'Dashboard.ReadStation': 'see a station dashboard',
  'Event.Archive': 'archive the event',
  'Event.Close': 'close the event',
  'Event.GoLive': 'take the event live',
  'Event.MarkReady': 'mark the event ready',
  'Event.Rehearse': 'start or end a rehearsal',
  'Event.Reopen': 'reopen a closed event',
  'Fallback.Declare': 'declare a paper fallback',
  'Fallback.Import': 'import paper fallback counts',
  'Footfall.Create': 'count room entries',
  'Gift.Redeem': 'redeem gifts',
  'Incident.Read': 'read incidents',
  'Incident.Report': 'report an incident',
  'Incident.Update': 'update an incident',
  'LostFound.Claim': 'hand back a lost item',
  'LostFound.CloseOut': 'close out lost property',
  'LostFound.Log': 'log a lost item',
  'LostPerson.Raise': 'raise a lost-person alert',
  'LostPerson.Resolve': 'resolve a lost-person alert',
  'People.AssignRole': "change someone's role",
  'People.Deactivate': 'deactivate a member',
  'People.Invite': 'invite people',
  'People.Read': 'see the people in the event',
  'People.Update': "edit a member's details",
  'Permissions.Edit': 'change role permissions',
  'Platform.AdministerEvent': 'administer the event as a platform admin',
  'Platform.CloneEvent': 'clone an event',
  'Platform.CreateEvent': 'create an event',
  'Platform.ManageAdmins': 'manage platform admins',
  'Platform.ManageOrganisation': 'manage the organisation',
  'Record.Void': 'void a record',
  'Registration.Create': 'register visitors',
  'Report.Export': 'export reports',
  'Report.Generate': 'see reports',
  'Roster.Edit': 'edit the roster',
  'Roster.ReadStation': "see a station's roster",
  'Schedule.Manage': 'schedule changes',
  'Self.Read': 'see your own details',
  'Settings.ManageEvent': 'change event settings',
  'Settings.ManagePrivacy': 'change privacy settings',
  'Settings.ManageSecurity': 'change security settings',
  'Settings.Read': "see the event's configuration",
  'Shift.CheckIn': 'check in to a shift',
  'Structure.Change': 'change stations, days and gift types',
  'Structure.Edit': 'edit the event setup',
  'Structure.Read': 'see the event setup',
  'Swap.Decide': 'approve or decline shift swaps',
  'Swap.Request': 'ask to swap a shift',
  'VisitorRecord.Read': 'see visitor details',
} as const satisfies Record<Action, string>;
