/**
 * Every `error.code` the API can return. The client switches on these, so they
 * are part of the contract and must not be renamed without a client change.
 */
export const ERROR_CODES = {
  // auth / authz
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  NOT_PROVISIONED: 'NOT_PROVISIONED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  FORBIDDEN: 'FORBIDDEN',
  STATION_SCOPE_DENIED: 'STATION_SCOPE_DENIED',

  // request shape
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',

  // idempotency
  IDEMPOTENCY_KEY_REUSE: 'IDEMPOTENCY_KEY_REUSE',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',

  // domain
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  ALREADY_VOIDED: 'ALREADY_VOIDED',
  NOT_ON_SHIFT: 'NOT_ON_SHIFT',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  NOT_CHECKED_IN: 'NOT_CHECKED_IN',
  STATION_INACTIVE: 'STATION_INACTIVE',
  STATION_DOES_NOT_COUNT_ENTRY: 'STATION_DOES_NOT_COUNT_ENTRY',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_ALREADY_STAMPED: 'CARD_ALREADY_STAMPED',
  ALERT_ALREADY_RESOLVED: 'ALERT_ALREADY_RESOLVED',

  // infrastructure
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
